"""Canonical KPI registry — exactly KPI-001 … KPI-120 with full metadata."""
from __future__ import annotations
from typing import Any, Dict, List


def _kpi(
    kpi_id: str,
    kpi_name: str,
    group: str,
    definition: str,
    formula: str,
    unit: str,
    level: str,
    visual_type: str,
    priority: str,
    dashboard_page: str,
    drilldown_behavior: str,
    drilldown_filter_preset: Dict[str, Any],
    api_endpoint: str = "/api/kpis/all-values",
) -> Dict[str, Any]:
    return {
        "kpi_id": kpi_id,
        "kpi_name": kpi_name,
        "name": kpi_name,
        "group": group,
        "definition": definition,
        "formula": formula,
        "unit": unit,
        "level": level,
        "visual_type": visual_type,
        "priority": priority,
        "dashboard_page": dashboard_page,
        "drilldown_behavior": drilldown_behavior,
        "drilldown_filter_preset": drilldown_filter_preset,
        "api_endpoint": api_endpoint,
    }


def build_kpi_registry() -> List[Dict[str, Any]]:
    reg: List[Dict[str, Any]] = []

    # A — Executive Portfolio (001–010)
    reg += [
        _kpi("KPI-001", "Total Procurement Portfolio Value", "Executive Portfolio",
             "Total financial value of all procurement records across Statements A/B/C/D.",
             "SUM(procurement_value)", "₹ Cr", "Executive", "KPI Card", "High",
             "Executive Procurement Overview", "filter_preset", {}),
        _kpi("KPI-002", "Total Procurement Item Count", "Executive Portfolio",
             "Total number of procurement items/tenders/POs.",
             "COUNT(record_id)", "Count", "Executive", "KPI Card", "High",
             "Executive Procurement Overview", "filter_preset", {}),
        _kpi("KPI-003", "Active Procurement Value", "Executive Portfolio",
             "Value currently progressing through PO, tender, or publish stages.",
             "PO Issued Value + Tender Under Process Value + Awaited Publish Value", "₹ Cr", "Executive", "KPI Card", "High",
             "Executive Procurement Overview", "filter_preset", {"is_active_pipeline": True}),
        _kpi("KPI-004", "Inactive Procurement Value", "Executive Portfolio",
             "Value stuck in expired, returned, cancelled, or closed cases.",
             "SUM(procurement_value WHERE status ∈ inactive)", "₹ Cr", "Executive", "KPI Card", "High",
             "Executive Procurement Overview", "filter_preset", {"is_inactive": True}),
        _kpi("KPI-005", "Active Procurement Share %", "Executive Portfolio",
             "Percentage of total portfolio that is active.",
             "Active Procurement Value / Total Portfolio Value × 100", "%", "Executive", "Gauge", "High",
             "Executive Procurement Overview", "filter_preset", {"is_active_pipeline": True}),
        _kpi("KPI-006", "Inactive Procurement Share %", "Executive Portfolio",
             "Percentage of portfolio value blocked or failed.",
             "Inactive Value / Total Portfolio Value × 100", "%", "Executive", "Gauge", "High",
             "Executive Procurement Overview", "filter_preset", {"is_inactive": True}),
        _kpi("KPI-007", "Average Procurement Value per Item", "Executive Portfolio",
             "Average financial value per procurement item.",
             "Total Portfolio Value / Item Count", "₹ Cr", "Executive", "KPI Card", "Medium",
             "Executive Procurement Overview", "filter_preset", {}),
        _kpi("KPI-008", "High-Value Procurement Count", "Executive Portfolio",
             "Number of procurement items above defined high-value threshold.",
             "COUNT(procurement_value > threshold)", "Count", "Executive", "KPI Card", "High",
             "Executive Procurement Overview", "filter_preset", {"value_band": "10+"}),
        _kpi("KPI-009", "Top 10 Item Concentration %", "Executive Portfolio",
             "Share of portfolio value held by top 10 procurement items.",
             "SUM(top10 value) / Total Portfolio × 100", "%", "Executive", "Pareto", "High",
             "Executive Procurement Overview", "filter_preset", {"top": 10, "sort_by": "procurement_value"}),
        _kpi("KPI-010", "Procurement Health Score", "Executive Portfolio",
             "Composite score showing overall procurement health.",
             "Weighted PO, payment, tender, backlog, inactive", "Score /100", "Executive", "Scorecard", "High",
             "Executive Procurement Overview", "filter_preset", {"is_risk": True}),
    ]

    # B — Statement (011–020)
    reg += [
        _kpi("KPI-011", "Statement A Value", "Statement",
             "Value where PO has been issued or execution started.",
             "SUM(procurement_value WHERE statement='A')", "₹ Cr", "Statement", "KPI Card", "High",
             "Statement Analysis", "filter_preset", {"statement": "A"}),
        _kpi("KPI-012", "Statement B Value", "Statement",
             "Value of tenders under process.",
             "SUM(procurement_value WHERE statement='B')", "₹ Cr", "Statement", "Bar", "High",
             "Statement Analysis", "filter_preset", {"statement": "B"}),
        _kpi("KPI-013", "Statement C Value", "Statement",
             "Value awaiting publish or retender.",
             "SUM(procurement_value WHERE statement='C')", "₹ Cr", "Statement", "Bar", "High",
             "Statement Analysis", "filter_preset", {"statement": "C"}),
        _kpi("KPI-014", "Statement D Value", "Statement",
             "Value expired, returned, cancelled, or inactive.",
             "SUM(procurement_value WHERE statement='D')", "₹ Cr", "Statement", "Bar", "High",
             "Statement Analysis", "filter_preset", {"statement": "D"}),
        _kpi("KPI-015", "Statement-Wise Count", "Statement",
             "Number of records in each statement.",
             "COUNT GROUP BY statement", "Count", "Statement", "Bar Chart", "Medium",
             "Statement Analysis", "filter_preset", {"dimension": "statement"}),
        _kpi("KPI-016", "Statement-Wise Share %", "Statement",
             "Percentage contribution of each statement to total value.",
             "Statement Value / Total × 100", "%", "Statement", "Donut Chart", "Medium",
             "Statement Analysis", "filter_preset", {"dimension": "statement"}),
        _kpi("KPI-017", "Average Value by Statement", "Statement",
             "Average item value within each statement.",
             "Statement Value / Statement Count", "₹ Cr", "Statement", "Bar Chart", "Medium",
             "Statement Analysis", "filter_preset", {"dimension": "statement"}),
        _kpi("KPI-018", "Statement Risk Weight", "Statement",
             "Risk severity weight by statement stage (A=20, B=40, C=70, D=90).",
             "Weighted score", "Score", "Statement", "Heatmap", "Medium",
             "Statement Analysis", "filter_preset", {"dimension": "statement", "metric": "risk_weight"}),
        _kpi("KPI-019", "Statement Execution Gap", "Statement",
             "Value not converted into PO.",
             "Total Procurement Value − PO Issued Value", "₹ Cr", "Statement", "Waterfall", "High",
             "Statement Analysis", "filter_preset", {"po_value_eq": True}),
        _kpi("KPI-020", "Statement Action Priority", "Statement",
             "Statement ranked by value, risk, and pending action.",
             "Rank(value + risk + pending)", "Rank", "Statement", "Ranked Table", "High",
             "Statement Analysis", "filter_preset", {"sort_by": "priority_score"}),
    ]

    # C — PO / Execution (021–030)
    reg += [
        _kpi("KPI-021", "Total PO Issued Value", "Execution (PO)",
             "Sum of PO values on issued PO lines.",
             "SUM(po_value)", "₹ Cr", "Execution", "KPI Card", "High",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True}),
        _kpi("KPI-022", "Total PO Issued Count", "Execution (PO)",
             "Count of records with PO issued.",
             "COUNT(po_value > 0 OR status PO Issued)", "Count", "Execution", "KPI Card", "High",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True}),
        _kpi("KPI-023", "PO Conversion %", "Execution (PO)",
             "PO issued value as share of total portfolio.",
             "PO Value / Total Portfolio × 100", "%", "Execution", "Gauge", "High",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True}),
        _kpi("KPI-024", "Execution Gap Value", "Execution (PO)",
             "Portfolio value not yet covered by PO.",
             "Total Portfolio − PO Issued Value", "₹ Cr", "Execution", "KPI Card", "High",
             "PO & Payment Monitoring", "filter_preset", {"po_value_eq": True}),
        _kpi("KPI-025", "PO Value by Department", "Execution (PO)",
             "PO value aggregated by department.",
             "SUM(po_value) GROUP BY department", "₹ Cr", "Execution", "Bar", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"dimension": "department", "metric": "po_value"}),
        _kpi("KPI-026", "PO Value by Category", "Execution (PO)",
             "PO value aggregated by category.",
             "SUM(po_value) GROUP BY category", "₹ Cr", "Execution", "Bar", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"dimension": "category", "metric": "po_value"}),
        _kpi("KPI-027", "High-Value PO Count", "Execution (PO)",
             "Count of POs above high-value threshold.",
             "COUNT(po_value > threshold)", "Count", "Execution", "KPI Card", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True, "value_band": "10+"}),
        _kpi("KPI-028", "PO Concentration %", "Execution (PO)",
             "Share of total PO value in top 10 PO lines.",
             "Top10 PO / Total PO × 100", "%", "Execution", "Bar", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"top": 10, "sort_by": "po_value"}),
        _kpi("KPI-029", "PO Execution Density", "Execution (PO)",
             "PO count per unit PO value (inverse scale).",
             "PO Count / PO Value", "1/Cr", "Execution", "KPI Card", "Low",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True}),
        _kpi("KPI-030", "PO Execution Health", "Execution (PO)",
             "Weighted composite of conversion, payment, and risk on PO lines.",
             "Weighted score", "Score", "Execution", "Gauge", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True, "is_risk": True}),
    ]

    # D — Payment (031–042)
    reg += [
        _kpi("KPI-031", "Total Amount Paid", "Payment",
             "Sum of paid amounts on PO lines.",
             "SUM(paid_amount)", "₹ Cr", "Payment", "KPI Card", "High",
             "PO & Payment Monitoring", "filter_preset", {"paid_amount_gt": True}),
        _kpi("KPI-032", "Outstanding Payment Value", "Payment",
             "PO value minus paid amount.",
             "SUM(po_value) − SUM(paid_amount)", "₹ Cr", "Payment", "KPI Card", "High",
             "PO & Payment Monitoring", "filter_preset", {"outstanding_amount_gt": True}),
        _kpi("KPI-033", "Payment Completion %", "Payment",
             "Paid amount over PO value.",
             "SUM(paid)/SUM(po)×100", "%", "Payment", "Gauge", "High",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True}),
        _kpi("KPI-034", "Payment Pending %", "Payment",
             "Outstanding over PO issued value.",
             "Outstanding / PO × 100", "%", "Payment", "Gauge", "High",
             "PO & Payment Monitoring", "filter_preset", {"outstanding_amount_gt": True}),
        _kpi("KPI-035", "Fully Paid PO Count", "Payment",
             "Records where paid ≥ po and po > 0.",
             "COUNT(Fully Paid)", "Count", "Payment", "KPI Card", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"payment_status": "fully_paid"}),
        _kpi("KPI-036", "Partially Paid PO Count", "Payment",
             "Records with partial payment against PO.",
             "COUNT(Partially Paid)", "Count", "Payment", "KPI Card", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"payment_status": "partially_paid"}),
        _kpi("KPI-037", "Unpaid PO Count", "Payment",
             "PO issued but no payment recorded.",
             "COUNT(Unpaid)", "Count", "Payment", "KPI Card", "High",
             "PO & Payment Monitoring", "filter_preset", {"payment_status": "unpaid"}),
        _kpi("KPI-038", "Outstanding by Department", "Payment",
             "Outstanding amount grouped by department.",
             "SUM(outstanding) GROUP BY department", "₹ Cr", "Payment", "Bar", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"dimension": "department", "metric": "outstanding_amount"}),
        _kpi("KPI-039", "Outstanding by Category", "Payment",
             "Outstanding amount grouped by category.",
             "SUM(outstanding) GROUP BY category", "₹ Cr", "Payment", "Bar", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"dimension": "category", "metric": "outstanding_amount"}),
        _kpi("KPI-040", "Payment Risk %", "Payment",
             "Outstanding as share of PO value.",
             "Outstanding / PO × 100", "%", "Payment", "Gauge", "High",
             "PO & Payment Monitoring", "filter_preset", {"outstanding_amount_gt": True}),
        _kpi("KPI-041", "Top Pending Payment Items", "Payment",
             "Ranked list by outstanding amount.",
             "ORDER BY outstanding DESC", "List", "Payment", "Table", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"top": 10, "sort_by": "outstanding_amount"}),
        _kpi("KPI-042", "Payment Efficiency Score", "Payment",
             "Weighted payment completion and pending exposure.",
             "Weighted score", "Score", "Payment", "Scorecard", "Medium",
             "PO & Payment Monitoring", "filter_preset", {"po_value_gt": True}),
    ]

    # E — Tender (043–052)
    tu = "Tender_Under_Process"
    reg += [
        _kpi("KPI-043", "Tender Under Process Value", "Tender Pipeline",
             "Value in tender under process (Statement B or status).",
             "SUM(procurement_value)", "₹ Cr", "Tender", "KPI Card", "High",
             "Tender Pipeline", "filter_preset", {"current_status": tu}),
        _kpi("KPI-044", "Tender Under Process Count", "Tender Pipeline",
             "Count of tender-under-process records.",
             "COUNT(*)", "Count", "Tender", "KPI Card", "High",
             "Tender Pipeline", "filter_preset", {"current_status": tu}),
        _kpi("KPI-045", "Tender Pipeline %", "Tender Pipeline",
             "Tender pipeline value over total portfolio.",
             "Tender Value / Total × 100", "%", "Tender", "Gauge", "High",
             "Tender Pipeline", "filter_preset", {"current_status": tu}),
        _kpi("KPI-046", "Tender Pipeline by Department", "Tender Pipeline",
             "Tender value by department.",
             "SUM GROUP BY department", "₹ Cr", "Tender", "Bar", "Medium",
             "Tender Pipeline", "filter_preset", {"dimension": "department", "current_status": tu}),
        _kpi("KPI-047", "Tender Pipeline by Category", "Tender Pipeline",
             "Tender value by category.",
             "SUM GROUP BY category", "₹ Cr", "Tender", "Bar", "Medium",
             "Tender Pipeline", "filter_preset", {"dimension": "category", "current_status": tu}),
        _kpi("KPI-048", "Average Tender Value", "Tender Pipeline",
             "Pipeline value divided by tender count.",
             "Pipeline / Count", "₹ Cr", "Tender", "KPI Card", "Medium",
             "Tender Pipeline", "filter_preset", {"current_status": tu}),
        _kpi("KPI-049", "High-Value Active Tender Count", "Tender Pipeline",
             "High / very high value tenders under process.",
             "COUNT", "Count", "Tender", "KPI Card", "Medium",
             "Tender Pipeline", "filter_preset", {"current_status": tu, "value_band": "10+,5-10"}),
        _kpi("KPI-050", "Tender Concentration %", "Tender Pipeline",
             "Top 10 tender value share of pipeline.",
             "Top10 / Pipeline × 100", "%", "Tender", "Bar", "Medium",
             "Tender Pipeline", "filter_preset", {"current_status": tu, "top": 10}),
        _kpi("KPI-051", "Tender Closure Priority", "Tender Pipeline",
             "Ranked tenders by value, stage, risk.",
             "Rank", "Rank", "Tender", "Table", "High",
             "Tender Pipeline", "filter_preset", {"current_status": tu, "sort_by": "priority_score"}),
        _kpi("KPI-052", "Tender Maturity Score", "Tender Pipeline",
             "Stage-weighted maturity (Unknown stage if missing).",
             "Weighted tender_stage", "Score", "Tender", "Funnel", "Medium",
             "Tender Pipeline", "filter_preset", {"current_status": tu, "dimension": "tender_stage"}),
    ]

    # F — Backlog (053–064)
    ap, rt = "Awaited_Publish", "Retender"
    reg += [
        _kpi("KPI-053", "Awaited Publish Value", "Backlog",
             "Value awaiting publish.",
             "SUM(procurement_value)", "₹ Cr", "Backlog", "KPI Card", "High",
             "Backlog & Retender", "filter_preset", {"current_status": ap}),
        _kpi("KPI-054", "Awaited Publish Count", "Backlog",
             "Count awaited publish.",
             "COUNT(*)", "Count", "Backlog", "KPI Card", "High",
             "Backlog & Retender", "filter_preset", {"current_status": ap}),
        _kpi("KPI-055", "Retender Value", "Backlog",
             "Value in retender status.",
             "SUM(procurement_value)", "₹ Cr", "Backlog", "KPI Card", "High",
             "Backlog & Retender", "filter_preset", {"current_status": rt}),
        _kpi("KPI-056", "Retender Count", "Backlog",
             "Count in retender.",
             "COUNT(*)", "Count", "Backlog", "KPI Card", "High",
             "Backlog & Retender", "filter_preset", {"current_status": rt}),
        _kpi("KPI-057", "Total Backlog Value", "Backlog",
             "Awaited publish plus retender value.",
             "SUM(backlog statuses)", "₹ Cr", "Backlog", "KPI Card", "High",
             "Backlog & Retender", "filter_preset", {"is_backlog": True}),
        _kpi("KPI-058", "Backlog %", "Backlog",
             "Backlog value over total portfolio.",
             "Backlog / Total × 100", "%", "Backlog", "Gauge", "High",
             "Backlog & Retender", "filter_preset", {"is_backlog": True}),
        _kpi("KPI-059", "Backlog by Department", "Backlog",
             "Backlog value by department.",
             "SUM GROUP BY department", "₹ Cr", "Backlog", "Bar", "Medium",
             "Backlog & Retender", "filter_preset", {"is_backlog": True, "dimension": "department"}),
        _kpi("KPI-060", "Backlog by Category", "Backlog",
             "Backlog value by category.",
             "SUM GROUP BY category", "₹ Cr", "Backlog", "Bar", "Medium",
             "Backlog & Retender", "filter_preset", {"is_backlog": True, "dimension": "category"}),
        _kpi("KPI-061", "Critical Backlog Value", "Backlog",
             "Backlog value where risk is critical or value above threshold.",
             "SUM(filtered)", "₹ Cr", "Backlog", "KPI Card", "High",
             "Backlog & Retender", "filter_preset", {"is_backlog": True, "risk_level": "Critical"}),
        _kpi("KPI-062", "Backlog Concentration %", "Backlog",
             "Top 10 backlog lines as share of backlog total.",
             "Top10 / Backlog × 100", "%", "Backlog", "Bar", "Medium",
             "Backlog & Retender", "filter_preset", {"is_backlog": True, "top": 10}),
        _kpi("KPI-063", "Publishing Delay Risk", "Backlog",
             "Awaited publish value weighted by priority / ageing.",
             "Weighted score", "Score", "Backlog", "Table", "High",
             "Backlog & Retender", "filter_preset", {"current_status": ap, "sort_by": "priority_score"}),
        _kpi("KPI-064", "Backlog Clearance Priority", "Backlog",
             "Ranked backlog by value, criticality, ageing.",
             "Rank", "Rank", "Backlog", "Table", "High",
             "Backlog & Retender", "filter_preset", {"is_backlog": True, "sort_by": "priority_score"}),
    ]

    # G — Failure / inactive (065–078)
    reg += [
        _kpi("KPI-065", "Expired Tender Value", "Failure / Inactive",
             "Value in expired status.", "SUM(procurement_value)", "₹ Cr", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"current_status": "Expired"}),
        _kpi("KPI-066", "Expired Tender Count", "Failure / Inactive",
             "Count expired.", "COUNT(*)", "Count", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"current_status": "Expired"}),
        _kpi("KPI-067", "Returned Case Value", "Failure / Inactive",
             "Value returned.", "SUM(procurement_value)", "₹ Cr", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"current_status": "Returned"}),
        _kpi("KPI-068", "Returned Case Count", "Failure / Inactive",
             "Count returned.", "COUNT(*)", "Count", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"current_status": "Returned"}),
        _kpi("KPI-069", "Cancelled Procurement Value", "Failure / Inactive",
             "Cancelled value.", "SUM(procurement_value)", "₹ Cr", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"current_status": "Cancelled"}),
        _kpi("KPI-070", "Cancelled Procurement Count", "Failure / Inactive",
             "Cancelled count.", "COUNT(*)", "Count", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"current_status": "Cancelled"}),
        _kpi("KPI-071", "Failed / Inactive Value", "Failure / Inactive",
             "Expired + returned + cancelled (+ closed).",
             "SUM(D-status)", "₹ Cr", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"is_inactive": True}),
        _kpi("KPI-072", "Failed / Inactive %", "Failure / Inactive",
             "Failed value over portfolio.", "Failed / Total × 100", "%", "Risk", "Gauge", "High",
             "Risk & Governance", "filter_preset", {"is_inactive": True}),
        _kpi("KPI-073", "Cancellation Rate", "Failure / Inactive",
             "Cancelled count over total count.", "COUNT / Total × 100", "%", "Risk", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"current_status": "Cancelled"}),
        _kpi("KPI-074", "Expiry Rate", "Failure / Inactive",
             "Expired count over total.", "COUNT / Total × 100", "%", "Risk", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"current_status": "Expired"}),
        _kpi("KPI-075", "Return Rate", "Failure / Inactive",
             "Returned count over total.", "COUNT / Total × 100", "%", "Risk", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"current_status": "Returned"}),
        _kpi("KPI-076", "Recoverable Failed Value", "Failure / Inactive",
             "Value marked recoverable.", "SUM(procurement_value)", "₹ Cr", "Risk", "KPI Card", "Medium",
             "Risk & Governance", "filter_preset", {"recovery_status": "Recoverable"}),
        _kpi("KPI-077", "Dead-Value Exposure", "Failure / Inactive",
             "Non-recoverable exposure.", "SUM(procurement_value)", "₹ Cr", "Risk", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"recovery_status": "Non-Recoverable"}),
        _kpi("KPI-078", "Failure Reason Analysis", "Failure / Inactive",
             "Count/value by failure reason (status-based proxy).",
             "GROUP BY failure proxy", "Mixed", "Risk", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"is_inactive": True, "dimension": "failure_reason"}),
    ]

    # H — Category (079–089)
    reg += [
        _kpi("KPI-079", "Equipment Procurement Value", "Category",
             "Total portfolio value for Equipment category.",
             "SUM(category=Equipment)", "₹ Cr", "Category", "Bar", "High",
             "Executive / Category", "filter_preset", {"category": "Equipment"}),
        _kpi("KPI-080", "Medicine Procurement Value", "Category",
             "Total portfolio value for Medicine category.",
             "SUM(category=Medicine)", "₹ Cr", "Category", "Bar", "High",
             "Executive / Category", "filter_preset", {"category": "Medicine"}),
        _kpi("KPI-081", "Category-Wise Procurement Share %", "Category",
             "Each category’s share of total value.", "Category / Total × 100", "%", "Category", "Donut", "Medium",
             "Executive / Category", "filter_preset", {"dimension": "category"}),
        _kpi("KPI-082", "Category-Wise Item Count", "Category",
             "Line count by category.", "COUNT GROUP BY category", "Count", "Category", "Bar", "Medium",
             "Executive / Category", "filter_preset", {"dimension": "category"}),
        _kpi("KPI-083", "Category Average Item Value", "Category",
             "Category value divided by count.", "AVG", "₹ Cr", "Category", "Bar", "Medium",
             "Executive / Category", "filter_preset", {"dimension": "category"}),
        _kpi("KPI-084", "Category PO Conversion %", "Category",
             "Category PO value over category total.", "PO/Total×100", "%", "Category", "Bar", "Medium",
             "Executive / Category", "filter_preset", {"dimension": "category", "metric": "po_conversion"}),
        _kpi("KPI-085", "Category Payment Completion %", "Category",
             "Paid over PO by category.", "Paid/PO×100", "%", "Category", "Bar", "Medium",
             "Executive / Category", "filter_preset", {"dimension": "category", "metric": "payment_completion"}),
        _kpi("KPI-086", "Category Backlog %", "Category",
             "Backlog value over category total.", "Backlog/Total×100", "%", "Category", "Bar", "Medium",
             "Executive / Category", "filter_preset", {"dimension": "category", "metric": "backlog"}),
        _kpi("KPI-087", "Category Risk Value", "Category",
             "High/critical risk value by category.", "SUM(risk lines)", "₹ Cr", "Category", "Heatmap", "High",
             "Executive / Category", "filter_preset", {"dimension": "category", "metric": "risk_value"}),
        _kpi("KPI-088", "Category Risk %", "Category",
             "Risk value over category total.", "%", "%", "Category", "Heatmap", "High",
             "Executive / Category", "filter_preset", {"dimension": "category", "metric": "risk_pct"}),
        _kpi("KPI-089", "Critical Category Pending Value", "Category",
             "Critical-risk pending value by category.", "SUM", "₹ Cr", "Category", "Table", "High",
             "Executive / Category", "filter_preset", {"dimension": "category", "risk_level": "Critical"}),
    ]

    # I — Department (090–102)
    reg += [
        _kpi("KPI-090", "Department Procurement Value", "Department",
             "SUM procurement by department.", "SUM", "₹ Cr", "Department", "Bar", "High",
             "Department View", "filter_preset", {"dimension": "department"}),
        _kpi("KPI-091", "Department Procurement Count", "Department",
             "COUNT by department.", "COUNT", "Count", "Department", "Bar", "Medium",
             "Department View", "filter_preset", {"dimension": "department"}),
        _kpi("KPI-092", "Department PO Value", "Department",
             "PO value by department.", "SUM(po)", "₹ Cr", "Department", "Bar", "High",
             "Department View", "filter_preset", {"dimension": "department", "metric": "po_value"}),
        _kpi("KPI-093", "Department Tender Pipeline Value", "Department",
             "Statement B value by department.", "SUM", "₹ Cr", "Department", "Bar", "Medium",
             "Department View", "filter_preset", {"dimension": "department", "current_status": tu}),
        _kpi("KPI-094", "Department Backlog Value", "Department",
             "Backlog value by department.", "SUM", "₹ Cr", "Department", "Bar", "High",
             "Department View", "filter_preset", {"dimension": "department", "is_backlog": True}),
        _kpi("KPI-095", "Department Failed Value", "Department",
             "Inactive value by department.", "SUM", "₹ Cr", "Department", "Bar", "High",
             "Department View", "filter_preset", {"dimension": "department", "is_inactive": True}),
        _kpi("KPI-096", "Department Share %", "Department",
             "Department share of portfolio.", "%", "%", "Department", "Donut", "Medium",
             "Department View", "filter_preset", {"dimension": "department"}),
        _kpi("KPI-097", "Department PO Conversion %", "Department",
             "PO / total by department.", "%", "%", "Department", "Bar", "Medium",
             "Department View", "filter_preset", {"dimension": "department", "metric": "po_conversion"}),
        _kpi("KPI-098", "Department Payment Completion %", "Department",
             "Paid / PO by department.", "%", "%", "Department", "Bar", "Medium",
             "Department View", "filter_preset", {"dimension": "department", "metric": "payment_completion"}),
        _kpi("KPI-099", "Department Backlog %", "Department",
             "Backlog / total by department.", "%", "%", "Department", "Bar", "Medium",
             "Department View", "filter_preset", {"dimension": "department", "metric": "backlog_pct"}),
        _kpi("KPI-100", "Department Risk Score", "Department",
             "Composite payment + backlog + failure risk.", "Score", "Score", "Department", "Heatmap", "High",
             "Department View", "filter_preset", {"dimension": "department", "metric": "risk_score"}),
        _kpi("KPI-101", "Department Action Pending Count", "Department",
             "Lines with action required by department.", "COUNT", "Count", "Department", "Bar", "High",
             "Action Tracker", "filter_preset", {"dimension": "department", "action_pending": True}),
        _kpi("KPI-102", "Department Escalation Priority", "Department",
             "Departments ranked by risk and volume.", "Rank", "Rank", "Department", "Table", "High",
             "Department View", "filter_preset", {"dimension": "department", "sort_by": "priority_score"}),
    ]

    # J — Governance / Risk / Action (103–120)
    reg += [
        _kpi("KPI-103", "Total Procurement Risk Value", "Governance / Risk",
             "Outstanding + backlog + failed value exposure.",
             "SUM components", "₹ Cr", "Governance", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"is_risk": True}),
        _kpi("KPI-104", "Risk Exposure %", "Governance / Risk",
             "Risk value over total portfolio.", "%", "%", "Governance", "Gauge", "High",
             "Risk & Governance", "filter_preset", {"is_risk": True}),
        _kpi("KPI-105", "High-Risk Case Count", "Governance / Risk",
             "Critical or high risk lines.", "COUNT", "Count", "Governance", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"risk_level": "Critical,High"}),
        _kpi("KPI-106", "High-Risk Case Value", "Governance / Risk",
             "Value at critical/high risk.", "SUM", "₹ Cr", "Governance", "KPI Card", "High",
             "Risk & Governance", "filter_preset", {"risk_level": "Critical,High"}),
        _kpi("KPI-107", "Risk by Statement", "Governance / Risk",
             "Risk-weighted value by statement.", "SUM GROUP", "₹ Cr", "Governance", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"dimension": "statement", "metric": "risk_value"}),
        _kpi("KPI-108", "Risk by Department", "Governance / Risk",
             "Risk exposure by department.", "SUM", "₹ Cr", "Governance", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"dimension": "department", "metric": "risk_value"}),
        _kpi("KPI-109", "Risk by Category", "Governance / Risk",
             "Risk exposure by category.", "SUM", "₹ Cr", "Governance", "Bar", "Medium",
             "Risk & Governance", "filter_preset", {"dimension": "category", "metric": "risk_value"}),
        _kpi("KPI-110", "Action Pending Count", "Governance / Actions",
             "Records with action required.", "COUNT", "Count", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"action_pending": True}),
        _kpi("KPI-111", "Action Pending Value", "Governance / Actions",
             "Portfolio value where action pending.", "SUM", "₹ Cr", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"action_pending": True}),
        _kpi("KPI-112", "Payment Follow-Up Value", "Governance / Actions",
             "Outstanding requiring payment follow-up.", "SUM(outstanding)", "₹ Cr", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"action_type": "Payment"}),
        _kpi("KPI-113", "Tender Closure Value", "Governance / Actions",
             "Tender pipeline pending closure.", "SUM", "₹ Cr", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"action_type": "Tender"}),
        _kpi("KPI-114", "Publish Pending Value", "Governance / Actions",
             "Awaited publish exposure.", "SUM", "₹ Cr", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"action_type": "Publish"}),
        _kpi("KPI-115", "Retender Approval Value", "Governance / Actions",
             "Retender-related value.", "SUM", "₹ Cr", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"action_type": "Retender"}),
        _kpi("KPI-116", "Official Decision Pending Value", "Governance / Actions",
             "High-value / official decision flag.", "SUM", "₹ Cr", "Governance", "KPI Card", "High",
             "Action Tracker", "filter_preset", {"official_decision_required": True}),
        _kpi("KPI-117", "Action Priority Index", "Governance / Actions",
             "Composite value + risk + ageing + criticality.", "Score", "Score", "Governance", "Table", "High",
             "Action Tracker", "filter_preset", {"sort_by": "priority_score"}),
        _kpi("KPI-118", "Recovery Potential Value", "Governance / Actions",
             "Recoverable failed/backlog value.", "SUM", "₹ Cr", "Governance", "KPI Card", "Medium",
             "Action Tracker", "filter_preset", {"recovery_status": "Recoverable"}),
        _kpi("KPI-119", "Recovery Potential %", "Governance / Actions",
             "Recoverable over blocked (inactive+backlog) value.", "%", "%", "Governance", "Gauge", "Medium",
             "Action Tracker", "filter_preset", {"recovery_status": "Recoverable"}),
        _kpi("KPI-120", "Next Best Action", "Governance / Actions",
             "Rule-based recommended action label from status/risk/payment.",
             "Rules engine", "Text", "Governance", "Narrative", "High",
             "Action Tracker", "filter_preset", {"action_pending": True}),
    ]

    assert len(reg) == 120, len(reg)
    ids = [r["kpi_id"] for r in reg]
    assert len(ids) == len(set(ids)), "duplicate kpi_id"
    for i in range(1, 121):
        assert f"KPI-{i:03d}" in ids, f"missing KPI-{i:03d}"
    return reg


KPI_REGISTRY: List[Dict[str, Any]] = build_kpi_registry()
REGISTRY_BY_ID: Dict[str, Dict[str, Any]] = {r["kpi_id"]: r for r in KPI_REGISTRY}


def get_registry() -> List[Dict[str, Any]]:
    return KPI_REGISTRY


def get_kpi_entry(kpi_id: str) -> Dict[str, Any] | None:
    kid = (kpi_id or "").strip().upper()
    if kid and not kid.startswith("KPI-"):
        if kid.isdigit():
            kid = f"KPI-{int(kid):03d}"
    return REGISTRY_BY_ID.get(kid)
